### ISSUE TITLE
Error with k-mer repeat count calculations; terminating program.

### ISSUE THREAD

**Issue by jp3117** [OSU-SRLab/MANTIS#21]
Hi,
I just installed the latest version and ran on Python 3.5. I had the following error message:
Microsatellite Analysis for Normal-Tumor InStability (v1.0.4)
python /home/marissa/MANTIS-master/kmer_repeat_counter.py \
-b /home/marissa/MANTIS-master/msi.test.bed \
-n /home/marissa/MANTIS-master/Sample-N1-EX-KD.bam \
-t /home/marissa/MANTIS-master/Sample_T1-EX-KD.bam \
-o /home/marissa/MANTIS-master/msi.kmer_counts.txt \
--min-read-quality 25.0 \
--min-locus-quality 30.0 \
--min-read-length 35 \
--genome /Volumes/Data/References/HiSeqAnalysisSoftware_UCSC_hg19/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa \
--threads 1
Getting repeat counts for repeat units (k-mers) ...
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/encodings/__init__.py", line 31, in <module>
    import codecs
  File "/usr/local/lib/python3.5/codecs.py", line 95
    *, _is_text_encoding=None):
     ^
SyntaxError: invalid syntax
Error with k-mer repeat count calculations; terminating program.

here is how the msi.test.bed file looks like:

chr1    9780710 9780720 (GAG)3  0   +
chr1    9780921 9780931 (GCT)3  0   +
chr1    9786990 9787000 (GAG)3  0   +
chr1    11182070    11182082    (TCT)4  0   +
chr1    11190676    11190686    (GTG)3  0   +
chr1    11190751    11190761    (TTC)3  0   +
chr1    11206852    11206863    (AC)5   0   +

Could you let me know how to solve the issue?
Thanks.

Marissa

**Comment by rbonneville** [comment]
What command are you using to run MANTIS? Also, please run 'python -V' and post the output.

**Comment by jp3117** [comment]
Thanks for your help. 

Here is the command:
python mantis.py --bedfile msi.test.bed --genome /Volumes/Data/References/HiSeqAnalysisSoftware_UCSC_hg19/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa -n ./Sample-N1-EX-KD.bam -t ./Sample-T1-EX-KD.bam -o msi.txt

pgmserver01 ~/MANTIS-master -> python -V
Python 3.5.1

**Comment by rbonneville** [comment]
We are investigating this; we are currently requesting to borrow a Mac to attempt to reproduce your error.

**Comment by messersc** [comment]
The only other reference to this error I can find is https://stackoverflow.com/questions/38124761/import-site-failed-use-v-for-traceback

Which python are you using? Can you also show the output of `which python` and `which python3`?

**Comment by jp3117** [comment]
Our system has two versions of python installed: python2.6 and python 3.5. I used python 3.5 for MANTIS.

which python
/usr/bin/python
which python3
/usr/local/bin/python3

Here is what I did in .bashrc file:

export PYTHONPATH="/usr/local/lib/python3.5”
alias python="/usr/local/bin/python3.5"

Hope it helps.

Thanks.

**Comment by rbonneville** [comment]
Although I have not yet been able to reproduce this issue, I suspect that this is the sequence of events:

1. Calling python from the shell to run mantis.py triggers the bash alias to python3. As Python 3.5 runs with PYTHONPATH pointing to the 3.5 libraries, it runs fine.
2. mantis.py calls a helper program kmer_repeat_counter.py. However, bash will only recognize alias if run through an interactive shell ([as explained here](https://stackoverflow.com/a/25099813)). Therefore, Python 2.7 runs kmer_repeat_counter.py.
3. PYTHONPATH is still pointing to the 3.5 libraries. Given syntactic differences between Python 2 and 3, Python 2.7 crashes upon attempting to import them.

This issue should be fixed by properly packaging MANTIS (see #20). Until then, this may be a potential workaround:

1. Create a folder in your home directory.
2. Softlink /usr/local/bin/python3.5 to a link named 'python' in that folder.
3. Set PATH to contain that folder first (e.g. <export PATH=/path/to/python_folder:$PATH>
4. Keep using your PYTHONPATH variable.

**Comment by rbonneville** [comment]
Try this version: https://github.com/rbonneville/MANTIS/tree/iss021

**Comment by rbonneville** [comment]
Hello @jp3117, do you have any further questions regarding this issue?

**Comment by jp3117** [comment]
Thanks for follow-up.

I haven’t had a chance to try it. I will let you know how it goes.

Best,
Marissa
