### ISSUE TITLE
Add the support of TUMOR-only sample

### ISSUE THREAD

**Issue by wangyugui** [OSU-SRLab/MANTIS#27]
Hi.

Can we add a option to run MANTIS with only a tumor sample?

The normal-tumor pair will have better result, but the tumor-sample-only mode will be Simpler ?

Best regards

**Comment by rbonneville** [comment]
Hello @wangyugui,


Unfortunately, the MANTIS algorithm cannot be applied to a tumor-only analysis, as it depends on comparison of repeat count distributions between two samples (a tumor and a matched normal). Although tumor-only MSI calling is possible in principle (for instance, this is offered by [Foundation Medicine](https://www.foundationmedicine.com/genomic-testing/foundation-one), a proprietary test), this is complicated by the fact that normal microsatellite lengths differ among different people, and that many NGS methods suffer impaired accuracy in microsatellites and other highly repetitive regions. Therefore, any tumor-only MSI test would require some model of normal variation in microsatellite-spanning reads given a particular type of assay. This is incompatible with the ability of MANTIS to be applied to matched tumor-normal pairs from a variety of sequencing instruments and NGS panels (provided that the same assay is used for both tumor and normal) without requiring training with a panel of normals.


If you have a panel of (not necessarily matched) normals available instead of tumor-normal pairs, you may wish to consider [mSINGS](https://www.ncbi.nlm.nih.gov/pubmed/24987110).

**Comment by wangyugui** [comment]
Thanks a lot for these info.
